### PR TITLE
[DOCS] Modify url in example/1-quickstart.ipynb

### PR DESCRIPTION
**Pull request by falconlee236**
## Description

Modify Full documentation url `latest` to `stable` in example/1-quickstart.ipynb

## Motivation and Context

When I click that url
```
Environment, Policy and Model
Full documentation of:

Base environment class [here](https://rl4co.readthedocs.io/en/latest/_content/api/envs/base.html)
Base policy class [here](https://rl4co.readthedocs.io/en/latest/_content/api/models/base.html)
Base model class [here](https://rl4co.readthedocs.io/en/latest/_content/api/algos/base.html)
```

the website shows this page
Screen Shot 2024-09-11 at 3 24 37 PM

this cannot access rl4co's official docs directly, so i change latest url to corresponding stable url.
- [ ] I have raised an issue to propose this change ([required](https://github.com/ai4co/rl4co/issues) for new features and bug fixes)

## Types of changes

What types of changes does your code introduce? Remove all that do not apply:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds core functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)
- [x] Example (update in the folder of examples)

## Checklist

Go over all the following points, and put an `x` in all the boxes that apply.
If you are unsure about any of these, don't hesitate to ask. We are here to help!

- [x] My change requires a change to the documentation.
- [x] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by fedebotu** [comment]
Hi @falconlee236 , thanks for spotting this!

Could you replace the ReadTheDocs URLs with the new [rl4.co](https://rl4.co/) website instead? For example:

https://rl4co.readthedocs.io/en/stable/docs/content/api/envs/base --> https://rl4.co/docs/content/api/envs/base/

**Comment by falconlee236** [comment]
> Hi @falconlee236 , thanks for spotting this!
> 
> Could you replace the ReadTheDocs URLs with the new [rl4.co](https://rl4.co/) website instead? For example:
> 
> https://rl4co.readthedocs.io/en/stable/docs/content/api/envs/base --> https://rl4.co/docs/content/api/envs/base/

Okay, I

**Comment by falconlee236** [comment]
> > Hi @falconlee236 , thanks for spotting this!
> > Could you replace the ReadTheDocs URLs with the new [rl4.co](https://rl4.co/) website instead? For example:
> > https://rl4co.readthedocs.io/en/stable/docs/content/api/envs/base --> https://rl4.co/docs/content/api/envs/base/
> 
> Okay, I change the url soon

Can you see my commit? @fedebotu

**Comment by fedebotu** [comment]
Yup, merging now. Thanks!

**Pull request merged**
