### PR TITLE
Update edge.py

### PR DESCRIPTION
**Pull request by bokveizen**
edge_attr should have the same length as the number of edges not nodes

### CODE REVIEW

**Review by fedebotu — COMMENTED** [review]
I think `n` was defined just few lines above, so in this case we should delete that as well?
This said it seems correct to me, could you verify @Furffico ?

**Comment by bokveizen** [comment]
> I think `n` was defined just few lines above, so in this case we should delete that as well? This said it seems correct to me, could you verify @Furffico ?

`n` is used for `get_full_graph_edge_index` though.

**Comment by Furffico** [comment]
> I think `n` was defined just few lines above, so in this case we should delete that as well? This said it seems correct to me, could you verify @Furffico ?

Yes, it is correct for `edge_attr` to have the same length as the number of edges.

**Comment by fedebotu** [comment]
LGTM!

**Pull request merged**
