### PR TITLE
[BugFix] python version

### PR DESCRIPTION
**Pull request by ShuN6211**
Enable to run "poetry install".

## Description

Update pyproject.toml to be enable to run `poetry install` and install rl4co project by poetry tool.
At current project, running `poetry install` may causes following errors.

```
The current project's Python requirement (>=3.8) is not compatible with some of the required packages Python requirement:
  - pyvrp requires Python <4.0,>=3.9, so it will not be satisfied for Python >=3.8,<3.9 || >=4.0
  - pyvrp requires Python <4.0,>=3.9, so it will not be satisfied for Python >=3.8,<3.9 || >=4.0
  - pyvrp requires Python <4.0,>=3.9, so it will not be satisfied for Python >=3.8,<3.9 || >=4.0
Because no versions of pyvrp match >0.8.2,<0.9.0 || >0.9.0,<0.9.1 || >0.9.1
 and pyvrp (0.8.2) requires Python <4.0,>=3.9, pyvrp is forbidden.
And because pyvrp (0.9.0) requires Python <4.0,>=3.9, pyvrp is forbidden.
So, because pyvrp (0.9.1) requires Python <4.0,>=3.9
 and rl4co depends on pyvrp (>=0.8.2), version solving failed.
  • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties
    For pyvrp, a possible solution would be to set the `python` property to ">=3.9,<4.0"
    For pyvrp, a possible solution would be to set the `python` property to ">=3.9,<4.0"
    For pyvrp, a possible solution would be to set the `python` property to ">=3.9,<4.0"

```
## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/ai4co/rl4co/issues) for new features and bug fixes)

## Types of changes

What types of changes does your code introduce? Remove all that do not apply:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds core functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)
- [ ] Example (update in the folder of examples)

## Checklist

Go over all the following points, and put an `x` in all the boxes that apply.
If you are unsure about any of these, don't hesitate to ask. We are here to help!

- [ ] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by fedebotu** [comment]
Hi @ShuN6211 , thanks for reporting this!

How about this instead:

```
pyvrp = { version = ">=0.8.2", optional = true, python = ">=3.9,<4.0" }
```

in the dependencies. This is because `pyvrp` is actually optionally and we would like not to constrain `rl4co` too much based on such dependencies. I tried `poetry install` and it works

**Comment by ShuN6211** [comment]
Hi @fedebotu , thanks for commenting!!
It' good to specify python version not in dependency but in optional scope. 😃
However, only changing a line regarding "pyvrp" still causes error in my environment. 
It seems numba(optional) and lightning requires numpy and numpy requires `python = ">=3.9"`
I tried following chunk and it works.
```
[tool.poetry.dependencies]
# Required dependencies
python = ">=3.9"
# Routing
pyvrp = { version = ">=0.8.2", optional = true, python = "<4.0" }

```
Procedure
- Create some venv. ( I use miniconda to create venv)
- Activate venv
- `python -m pip install poetry`
- `rm poetry.lock`
- `poetry install`

Side notes
- machine: M1 macbook Pro 2021, macOS Ventura13.4.1
-  python version: 3.10
- poetry version:  1.5.0

**Comment by fedebotu** [comment]
I see! This is better, in my opinion, since we may want to restrict a lower version of Python rather than the upper one (Python 3.8 is pretty old anyway). To be honest, though, I'm not a fan of restricting the main Python version because of some optional dependency, so if there was another way, I'd rather go for that :) 

Thoughts @cbhua @LTluttmann?

**Comment by ShuN6211** [comment]
Hi @fedebotu , thanks for sharing the dropping support for python 3.8 in newest PyTorch Lightning!!
I added revert commit and new one that reflect conversation between us. If you don't prefer revert, I will reopen PR.

**Comment by cbhua** [comment]
@ShuN6211 Thanks for reporting the bug about the Python version!

Considering the status of Python versions from the [official release cycle](https://devguide.python.org/versions/) that Python 3.8's end-of-life day is `2024-10`, I agree that let's stop the support for Python 3.8.

**Review by cbhua — APPROVED** [review]

**Pull request merged**
